### ISSUE TITLE
Can't satisfy CONNECT request - operation was canceled

### ISSUE THREAD

**Issue by kakaska** [Snawoot/hola-proxy#121]
After 2 hours using the proxy it stops working with these errors:

![hola](https://github.com/user-attachments/assets/24b45b38-fefa-4256-bf68-7347e1d32953)

Would it be possible to automatically reconnect if this is happening?

**Comment by Snawoot** [comment]
Hello!

I just checked and I see no issue after 2 hours running hola-proxy. Also I see server specified in logs on your screenshot right now responds properly.

Two things could have happened:
* Chosen server temporarily went down for maintenance. However, I checked it right away when you created an issue and it seems it was not the case.
* Server is getting blocked by filters in your country after some detection period.

First case does not happen too often. But if second one takes place, probably it will be more reasonable to consider some other censorship circumvention solution, this one is always on the brim of failure and countermeasures won't be very efficient.

Detection of such situations from the code is kind of possible, but

* Observing network errors passively is not very reliable, because there may be plenty of other reasons for connection timeout.
* Active checks of some well-known URL could work, but it makes this solution have very distinct behavior from other hola clients and may be prone to detection and bans.

We could rotate server endpoint proactively, just like we do with credentials, but it will make exit IP rotate frequently as well, which is not very desirable behavior.

For now I suggest just periodic restarts. Let's observe this issue a little bit longer and see if there any way around it. Please let me know how often such disruptions happen, what is your ISP and if restarts always help.
