### ISSUE TITLE
Initate all connections via proxy if requested

### ISSUE THREAD

**Issue by rany2** [Snawoot/hola-proxy#33]
```
env http{,s}_proxy=socks5://127.0.0.1:9050 hola-proxy....
```

should have all connections initiated via Tor. Basically something like `Tor socks <-> Hola proxy (<-> fallback Hola proxy if blocked)`

**Comment by rany2** [comment]
Not sure if this is very complicated to implement as it would involve some kind of `proxychains`-like implementation

**Comment by Snawoot** [comment]
Yes, it will require stacking of proxies on each other and also it will require to adapt DNS resolver to use proxy when requests need address rewriting. Later is not so straightforward because our resolve lib doesn't allow customize it's network interactions.

While it's a nice feature to have, it's use case is pretty narrow, there is a lot of work required to implement it, and even then support will be incomplete. For this reason proxy support is a non-goal for now (however previous versions had such support for *some* requests by occasion).

**Comment by Snawoot** [comment]
Reopening issues since implementation appears approachable with new stacked connection dialers.

**Comment by Snawoot** [comment]
I guess env variable is not a best option because if you normally use hola proxy for everything, you set address of hola-proxy port system-wide. Probably command-line option will do better.

**Comment by Snawoot** [comment]
Released in `v1.5.0`
