### ISSUE TITLE
How to use in Android

### ISSUE THREAD

**Issue by kingamir021** [Snawoot/hola-proxy#44]
Hi
How can this tool be used in Android?

**Comment by Snawoot** [comment]
Hi!

Just like any other console application on android: run it with Termux or Qute or other shell of your choice. I used Qute since it has convenient option to create shortcuts to run scripts. In order to redirect traffic via hola-proxy daemon you may use [AdGuard for Android](https://adguard.com/en/article/adblock-for-android.html), which has an option to redirect all traffic via proxy. Don't forget to add Termux or Qute or other shell to exceptions of AdGuard application. Otherwise traffic will be looped and nothing will work.

Unfortunately, an illustrated guide for this is not present at this moment. It will be nice if someone contribute one for Android.
