### ISSUE TITLE
github.com:443 denied

### ISSUE THREAD

**Issue by govnotest** [Snawoot/hola-proxy#7]
Hi, my previous problem was with iptables rules, but now I can’t connect to github.com even clearing all the rules. When connected, the hola proxy produces:

PROXY   : 2020/06/17 11:54:08 handler.go:41: INFO     Request: 127.0.0.1:39904 CONNECT //github.com:443
PROXY   : 2020/06/17 11:54:09 handler.go:75: INFO     Request //github.com:443 denied by upstream. Rescuing it with resolve&rewrite workaround.

**Comment by Snawoot** [comment]
Hi,

This message is OK because hola proxies deny access to vital resources in order to push users to paid accounts. So, direct requests to connect to github.com domain get rejected. My hola-proxy client workarounds such blocks: it resolves given name with DNS-over-HTTPS resolver and substitutes domain name with IP address in request. This way connection passes.

**Comment by govnotest** [comment]
I checked the client’s work in firefox 77.0.1 and everything works fine, but in chromium getting this error

**Comment by Snawoot** [comment]
Does github.com opens in your chromium?

**Comment by govnotest** [comment]
Yes, without  hola-proxy github.com opens. Maybe this is due to the my chromium version, i'm using the  65 version with SwitchyOmega extension

**Comment by Snawoot** [comment]
Which error is observed in chromium when github.com page requested?

**Comment by govnotest** [comment]
ERR_TUNNEL_CONNECTION_FAILED

**Comment by govnotest** [comment]
problem solved
