### ISSUE TITLE
Received HTTP code 407 from proxy after CONNECT

### ISSUE THREAD

**Issue by tia3** [Snawoot/hola-proxy#9]
Hi there,

Sorry for disturbing again. Finaly I got a Chinese proxy to fetch credentials for Hola. But if I tri to fetch any site, I got back 407 http error, that should means authentication error.
As earlier you wrote the code should work properly. I just want to get a kind of support, where or how to start debug this issue.

`[root@host ~]# https_proxy=200.18.248.76:80 ~/go/bin/hola-proxy -country hu -verbosity 0
MAIN    : 2021/01/01 21:25:01 main.go:95: INFO     Constructing fallback DNS upstream...
MAIN    : 2021/01/01 21:25:01 main.go:101: INFO     Initializing configuration provider...
MAIN    : 2021/01/01 21:25:03 main.go:114: INFO     Endpoint: zagent1755.hola.org:22222
MAIN    : 2021/01/01 21:25:03 main.go:115: INFO     Starting proxy server...
PROXY   : 2021/01/01 21:25:18 handler.go:41: INFO     Request: 127.0.0.1:43454 GET http://google.com/
PROXY   : 2021/01/01 21:25:20 handler.go:214: INFO     127.0.0.1:43454 GET http://google.com/ 407 Auth Failed suspicious
PROXY   : 2021/01/01 21:25:34 handler.go:41: INFO     Request: 127.0.0.1:43464 CONNECT //google.com:443
PROXY   : 2021/01/01 21:26:01 handler.go:41: INFO     Request: 127.0.0.1:43480 CONNECT //google.com:443
PROXY   : 2021/01/01 21:26:07 handler.go:41: INFO     Request: 127.0.0.1:43484 GET http://google.com/
PROXY   : 2021/01/01 21:26:08 handler.go:214: INFO     127.0.0.1:43484 GET http://google.com/ 407 Auth Failed suspicious
PROXY   : 2021/01/01 21:26:27 handler.go:41: INFO     Request: 127.0.0.1:43494 GET http://google.com/
PROXY   : 2021/01/01 21:26:28 handler.go:214: INFO     127.0.0.1:43494 GET http://google.com/ 407 Auth Failed suspicious`

Curl from the same server:
`[root@host ~]# curl -x 127.0.0.1:8080 https://google.com
curl: (56) Received HTTP code 407 from proxy after CONNECT`

Thank you in advice

**Comment by Snawoot** [comment]
Hi!

No problem!

Yep, chinese IPs are suspicious and Hola openly says it: `407 Auth Failed suspicious`.

I've tested configuration above (with HTTP_PROXY env var) with another instance of hola-proxy to bootstrap credentials. It worked, but it seems you have chicken and egg problem: you can't have proxy due to lack of credible IP and can't originate proxy request from credible IP due to lack of access to proxy.

What you may have to workaround this:

* Try other proxy which appears to be less suspicious to Hola.
* Use TOR as HTTP proxy to bootstrap `hola-proxy`. Here is [TOR installation instructions for Centos](https://community.torproject.org/relay/setup/guard/centosrhel/). By default TOR daemon provides only SOCKS5 proxy. You'll have edit `/etc/tor/torrc` and add line `HTTPTunnelPort 9080` in order to enable HTTP proxy which will be available as `HTTP_PROXY=localhost:9080`.
* Try alternatives to this project. For example, [docker-rotating-proxy](https://github.com/39ff/docker-rotating-proxy), which, by the way, includes this project as one of upstream proxies.
* Try Browsec proxy: `https://nl1.postls.com:443`. In order to make `hola-proxy` connect to it, you'll need TCP<->TLS adapter like this: `socat TCP-LISTEN:9000,reuseaddr openssl:nl1.postls.com:443` and then run `HTTP_PROXY=localhost:9000 ~/go/bin/hola-proxy -country hu -verbosity 0`. Source: https://skolk.livejournal.com/tag/browsec
* You also may consider use of paid proxies from P2P proxy broker like [packetstream.io](https://packetstream.io/). Since you need them only to bootstrap credentials, it'll be almost free for you.
* ... Myriad of other options, depending on your use case, conditions and personal preferences.

**Comment by Snawoot** [comment]
Also another option: free SOCKS5 from VPN Unlimited https://www.vpnunlimitedapp.com/help/specials/what-is-socks5-proxy

Use like this: `HTTP_PROXY=socks5://vpn:unlimited@142.93.68.63:2435 ~/go/bin/hola-proxy -country us`
